---
abstract: 'busy or delaying activity; bustle; fuss.'
author:
  - 'Красимир Беров <berov@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.3800
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
keywords:
  - Ado
  - Mojolicious
  - web
  - ERP
  - REST
  - CMS
  - enterprise
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ado
provides:
  Ado:
    file: lib/Ado.pm
    version: 0.20
  Ado::Build:
    file: lib/Ado/Build.pm
    version: 0
  Ado::BuildPlugin:
    file: lib/Ado/BuildPlugin.pm
    version: 0
  Ado::Command:
    file: lib/Ado/Command.pm
    version: 0
  Ado::Control:
    file: lib/Ado/Control.pm
    version: 0
  Ado::Control::Ado:
    file: lib/Ado/Control/Ado.pm
    version: 0
  Ado::Control::Ado::Default:
    file: lib/Ado/Control/Ado/Default.pm
    version: 0
  Ado::Control::Ado::Users:
    file: lib/Ado/Control/Ado/Users.pm
    version: 0
  Ado::Control::Default:
    file: lib/Ado/Control/Default.pm
    version: 0
  Ado::Model:
    file: lib/Ado/Model.pm
    version: 0.01
  Ado::Model::Domains:
    file: lib/Ado/Model/Domains.pm
    version: 0
  Ado::Model::Groups:
    file: lib/Ado/Model/Groups.pm
    version: 0
  Ado::Model::Sessions:
    file: lib/Ado/Model/Sessions.pm
    version: 0
  Ado::Model::SessionsOld:
    file: lib/Ado/Model/SessionsOld.pm
    version: 0
  Ado::Model::SqliteSequence:
    file: lib/Ado/Model/SqliteSequence.pm
    version: 0
  Ado::Model::UserGroup:
    file: lib/Ado/Model/UserGroup.pm
    version: 0
  Ado::Model::Users:
    file: lib/Ado/Model/Users.pm
    version: 0
  Ado::Plugin:
    file: lib/Ado/Plugin.pm
    version: 0
  Ado::Plugin::Routes:
    file: lib/Ado/Plugin/Routes.pm
    version: 0
recommends:
  DBD::SQLite: 1.40
  Devel::Cover: 1.08
  Perl::Tidy: 0
  Test::CheckManifest: 0
  Test::Perl::Critic: 0
  Test::Pod: 1.48
  Test::Pod::Coverage: 1.08
requires:
  EV: 4.15
  IO::Socket::IP: 0.24
  Mojolicious: 4.63
  Mojolicious::Plugin::DSC: 0.999
  perl: 5.014000
resources:
  bugtracker: http://github.com/kberov/Ado/issues
  license: http://www.gnu.org/licenses/lgpl-3.0.txt
  repository: http://github.com/kberov/Ado
version: 0.20
