---
abstract: 'busy or delaying activity; bustle; fuss.'
author:
  - 'Красимир Беров <berov@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ado
provides:
  Ado:
    file: lib/Ado.pm
    version: 0.10
  Ado::Build:
    file: lib/Ado/Build.pm
    version: 0
  Ado::Command:
    file: lib/Ado/Command.pm
    version: 0
  Ado::Control:
    file: lib/Ado/Control.pm
    version: 0
  Ado::Control::Ado:
    file: lib/Ado/Control/Ado.pm
    version: 0
  Ado::Control::Ado::Default:
    file: lib/Ado/Control/Ado/Default.pm
    version: 0
  Ado::Control::Default:
    file: lib/Ado/Control/Default.pm
    version: 0
recommends:
  DBD::SQLite: 1.40
  DBD::mysql: 4.025
  Devel::Cover: 1.08
  Perl::Tidy: 0
  Test::CheckManifest: 0
  Test::Perl::Critic: 0
  Test::Pod: 1.48
  Test::Pod::Coverage: 1.08
requires:
  Mojolicious: 4.57
  Mojolicious::Plugin::DSC: 0.997
  perl: 5.016003
resources:
  bugtracker: http://github.com/kberov/Ado/issues
  license: http://www.gnu.org/licenses/lgpl-3.0.txt
  repository: http://github.com/kberov/Ado
version: 0.10
